# Assignment #2

## Calculate similarity of users in your data set

‐ Choosing three similarity measures

‐ Mandatory: COS and PCC

‐ Choose another one anything you want

### Using Jester-data-1 ( only contains 24983 users )

### About Jester-data-1
1. 3 Data files contain anonymous ratings data from 73,421 users.
2. Data files are in .zip format, when unzipped, they are in Excel (.xls) format
3. Ratings are real values ranging from -10.00 to +10.00 (the value "99" corresponds to "null" = "not rated").
4. One row per user
5. The first column gives the number of jokes rated by that user. The next 100 columns give the ratings for jokes 01 - 100.
6. The sub-matrix including only columns {5, 7, 8, 13, 15, 16, 17, 18, 19, 20} is dense. Almost all users have rated those jokes (see discussion of "universal queries" in the above paper).

### About Data
1. user_id  : starts with 1 ends with 24983
2. joke_num : starts with 1 ends with 100
3. the first column (which is joke_num == 0) gives the number of jokes rated by that user
4. the value "99" corresponds to "null" = "not rated"

In [1]:
import numpy as np
import pandas as pd

from _func import Call_Jester
from _func import Similarity

In [2]:
_jester=Call_Jester._Import_Data(r"_data\jester-data-1.csv")
jester_data = _jester._Call_Jester()  # jester.mu
df = pd.DataFrame(jester_data)

In [3]:
jester = Similarity._similarity(jester_data)

In [4]:
jester.COS()

array([[0.        , 0.59913854, 0.78912302, ..., 0.66318765, 0.80579778,
        0.75393565],
       [0.59913854, 0.        , 0.91246041, ..., 0.76418564, 0.89201565,
        0.80199813],
       [0.78912302, 0.91246041, 0.        , ..., 0.84957223, 0.89765365,
        0.92210132],
       ...,
       [0.66318765, 0.76418564, 0.84957223, ..., 0.        , 0.83851185,
        0.79228678],
       [0.80579778, 0.89201565, 0.89765365, ..., 0.83851185, 0.        ,
        0.91828837],
       [0.75393565, 0.80199813, 0.92210132, ..., 0.79228678, 0.91828837,
        0.        ]])

In [5]:
jester.PCC()

array([[-1.        , -0.30896816,  0.05702589, ...,  0.12035605,
         0.17642222,  0.33185527],
       [-0.30896816, -1.        , -0.00181169, ..., -0.17236068,
         0.12427836, -0.276338  ],
       [ 0.05702589, -0.00181169, -1.        , ..., -0.13188322,
         0.05186439, -0.04820536],
       ...,
       [ 0.12035605, -0.17236068, -0.13188322, ..., -1.        ,
         0.15770154,  0.05554445],
       [ 0.17642222,  0.12427836,  0.05186439, ...,  0.15770154,
        -1.        ,  0.33555199],
       [ 0.33185527, -0.276338  , -0.04820536, ...,  0.05554445,
         0.33555199, -1.        ]])

In [6]:
jester.JAC()

array([[1.        , 0.7       , 0.52564103, ..., 0.7       , 0.48684211,
        0.90540541],
       [0.7       , 1.        , 0.47      , ..., 0.98      , 0.42424242,
        0.69      ],
       [0.52564103, 0.47      , 1.        , ..., 0.48484848, 0.69811321,
        0.57333333],
       ...,
       [0.7       , 0.98      , 0.48484848, ..., 1.        , 0.42424242,
        0.69      ],
       [0.48684211, 0.42424242, 0.69811321, ..., 0.42424242, 1.        ,
        0.51351351],
       [0.90540541, 0.69      , 0.57333333, ..., 0.69      , 0.51351351,
        1.        ]])

In [7]:
jester.MSD()

array([[0.        , 0.32687561, 0.31706716, ..., 0.16475636, 0.18977628,
        0.20437134],
       [0.32687561, 0.        , 0.16538852, ..., 0.21625323, 0.10537391,
        0.19372376],
       [0.31706716, 0.16538852, 0.        , ..., 0.27804044, 0.16089037,
        0.13444   ],
       ...,
       [0.16475636, 0.21625323, 0.27804044, ..., 0.        , 0.15188669,
        0.17539395],
       [0.18977628, 0.10537391, 0.16089037, ..., 0.15188669, 0.        ,
        0.08919439],
       [0.20437134, 0.19372376, 0.13444   , ..., 0.17539395, 0.08919439,
        0.        ]])

In [8]:
jester.JMSD(1)

array([[1.        , 0.47118708, 0.35897752, ..., 0.58467055, 0.39445102,
        0.72036649],
       [0.47118708, 1.        , 0.3922674 , ..., 0.76807183, 0.37953834,
        0.55633061],
       [0.35897752, 0.3922674 , 1.        , ..., 0.350041  , 0.58579351,
        0.4962544 ],
       ...,
       [0.58467055, 0.76807183, 0.350041  , ..., 1.        , 0.35980565,
        0.56897818],
       [0.39445102, 0.37953834, 0.58579351, ..., 0.35980565, 1.        ,
        0.46771099],
       [0.72036649, 0.55633061, 0.4962544 , ..., 0.56897818, 0.46771099,
        1.        ]])